spring:
  application:
    name: spring-cache-test-x1
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  cache:
    cache-names: "fractal-crate-cahe"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=10m"
server:
  port: 8120
