spring:
  application:
    name: spring-cache-test-x5
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  cache:
    cache-names: "fractal-crate-cache"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=10m"
server:
  port: 8124
