spring:
  application:
    name: spring-cache-test-x6
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  cache:
    cache-names: "cache-controll"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=3m"
server:
  port: 8125
