spring:
  application:
    name: spring-cache-test-x4
  thymeleaf:
    cache: false
    prefix: classpath:/templates
  cache:
    cache-names: "fractal-crate-cache"
    caffeine:
      spec: "maximumSize=500,expireAfterAccess=10m"
server:
  port: 8123
